theme = "hyde"
baseURL = "https://rockyrna.org/"
languageCode = "en-us"
title = "Rocky Mountain RNA Meeting"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    # description = "Regional RNA Meeting in Denver, CO"
    description = " "
    logo = "logo-inverse.svg"
