theme = "hyde"
baseURL = "https://rockyrna.org/"
languageCode = "en-us"
title = "Rocky Mountain Regional RNA Meetings"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    description = " " # don't change
    truncate = true
